### ISSUE TITLE
bug: make it work with current catalogs

### ISSUE THREAD

**Issue by rwaffen** [betadots/container-puppet-catalog-graph-viewer#2]
does not work with current catalogs from puppet7.

```
hierarchy_graph.js:68 Uncaught TypeError: Cannot read properties of undefined (reading 'edges')
    at hierarchy_graph.js:68:18
    at Object.<anonymous> (d3.v3.min.js:1:11277)
    at Object.t (d3.v3.min.js:1:1565)
    at XMLHttpRequest.i (d3.v3.min.js:1:10137)
```

used catalog: 
[catalog.json](https://github.com/betadots/container-puppet-catalog-graph-viewer/files/15417720/catalog.json)

**Comment by tuxmea** [comment]
Even if one removes https://github.com/betadots/container-puppet-catalog-graph-viewer/blob/a6a633b09e89413b0c7be56eba59fec00b4b8a94/files/hierarchy_graph.js#L53 we receive errors.

New error:
```
Uncaught TypeError: object is undefined
    resource_ref http://localhost:8080/hierarchy_graph.js:33
    edge_index   http://localhost:8080/hierarchy_graph.js:78
    n            https://d3js.org/d3.v3.min.js:3
    s            https://d3js.org/d3.v3.min.js:3
    forEach      https://d3js.org/d3.v3.min.js:3
    n            https://d3js.org/d3.v3.min.js:3
    map          https://d3js.org/d3.v3.min.js:3
    <anonymous>  http://localhost:8080/hierarchy_graph.js:79
    send         https://d3js.org/d3.v3.min.js:1
    t            https://d3js.org/d3.v3.min.js:1
    i            https://d3js.org/d3.v3.min.js:1
    Cn           https://d3js.org/d3.v3.min.js:1
    json         https://d3js.org/d3.v3.min.js:5
    <anonymous>  http://localhost:8080/hierarchy_graph.js:50
hierarchy_graph.js:33:3
```

**Comment by rwaffen** [comment]
this is how the agent generates the dot files:
https://github.com/search?q=repo%3Apuppetlabs%2Fpuppet+graph&type=code

**Comment by rwaffen** [comment]
please add catalog with dependency cycle

**Comment by marcusdots** [comment]
[pe.marcus.betadots.training.json](https://github.com/user-attachments/files/17478361/pe.marcus.betadots.training.json)

Example Catalogue from an empty Puppet Enterprise installation (1,800 ressources)

**Comment by oneiros** [comment]
![image](https://github.com/user-attachments/assets/81768ef2-0f18-47d0-9f65-b626d7d0401c)

**Comment by marcusdots** [comment]
The graph visualizes this piece of puppet code
https://github.com/marcusdots/buggedcontrolrepo/blob/catalog_visualisation/manifests/site.pp
